import type { Part } from "./types";

type Seed = Omit<Part, "id" | "createdAt" | "updatedAt">;

/**
 * Demo catalogue for the counter. Every line is marked demo: the prices,
 * weights and stock figures are placeholders, and the pictures are drawings
 * (scripts/make-demo-art.mjs), not photographs of stock.
 */
export const SEED_PARTS: Seed[] = [
  // --- Rough Gems ----------------------------------------------------------
  {
    sku: "RG-SAP-P1",
    title: "Rough Sapphire Parcel — Mixed Blue",
    brand: "Demo",
    category: "rough-gems",
    description:
      "Demo listing. Mine-run blue sapphire rough, sold by the parcel for cutters. Weights, colour and origin shown are placeholders until a live parcel is listed.",
    packSize: "10 ct parcel",
    stockQty: 6,
    reorderPoint: 2,
    price: 420,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "rough-sapphire-parcel",
  },
  {
    sku: "RG-RUB-C1",
    title: "Rough Ruby Crystal — Single Piece",
    brand: "Demo",
    category: "rough-gems",
    description:
      "Demo listing. A single tabular ruby crystal as it comes off the parcel, uncut. Every figure here stands in until a live piece is listed.",
    packSize: "1 piece",
    stockQty: 3,
    reorderPoint: 1,
    price: 680,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "rough-ruby-crystal",
  },
  {
    sku: "RG-EME-P1",
    title: "Rough Emerald Prism — Beryl",
    brand: "Demo",
    category: "rough-gems",
    description:
      "Demo listing. Hexagonal beryl prism for a cutter or a collector shelf. Clarity, weight and origin are placeholders.",
    packSize: "1 piece",
    stockQty: 4,
    reorderPoint: 1,
    price: 540,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "rough-emerald-prism",
  },
  {
    sku: "RG-GAR-P1",
    title: "Rough Garnet Parcel — Mine Run",
    brand: "Demo",
    category: "rough-gems",
    description:
      "Demo listing. Water-worn garnet rough sorted by size, priced by the parcel. Figures stand in until a live parcel is listed.",
    packSize: "25 ct parcel",
    stockQty: 9,
    reorderPoint: 3,
    price: 160,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "rough-garnet-parcel",
  },
  {
    sku: "RG-AME-C1",
    title: "Amethyst Cluster on Matrix",
    brand: "Demo",
    category: "rough-gems",
    description:
      "Demo listing. Amethyst points on their matrix bed, the kind that goes on a shelf rather than into a setting. Placeholder figures.",
    packSize: "1 piece",
    stockQty: 5,
    reorderPoint: 2,
    price: 95,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "rough-amethyst-cluster",
  },

  // --- Loose Diamonds ------------------------------------------------------
  {
    sku: "LD-RB-050",
    title: "Round Brilliant 0.50 ct",
    brand: "Demo",
    category: "loose-diamonds",
    description:
      "Demo listing. Carat weight, colour and clarity shown are placeholders; a live stone is quoted with the grading we hold for it, and you see it before you commit.",
    packSize: "1 stone",
    stockQty: 4,
    reorderPoint: 1,
    price: 1150,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "diamond-round-brilliant",
  },
  {
    sku: "LD-RB-101",
    title: "Round Brilliant 1.01 ct",
    brand: "Demo",
    category: "loose-diamonds",
    description:
      "Demo listing. The figures are placeholders; a live stone is quoted with the grading we hold for it, and you see it before you commit.",
    packSize: "1 stone",
    stockQty: 2,
    reorderPoint: 1,
    price: 5400,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "diamond-round-large",
  },
  {
    sku: "LD-EC-072",
    title: "Emerald Cut 0.72 ct",
    brand: "Demo",
    category: "loose-diamonds",
    description:
      "Demo listing. A step cut shows its body colour and its clarity plainly, so we quote it against the grading we hold. All figures here are placeholders.",
    packSize: "1 stone",
    stockQty: 3,
    reorderPoint: 1,
    price: 2100,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "diamond-emerald-cut",
  },
  {
    sku: "LD-OV-090",
    title: "Oval Brilliant 0.90 ct",
    brand: "Demo",
    category: "loose-diamonds",
    description:
      "Demo listing. Length-to-width ratio and grading come with the live stone; everything shown here is a placeholder.",
    packSize: "1 stone",
    stockQty: 2,
    reorderPoint: 1,
    price: 3300,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "diamond-oval",
  },
  {
    sku: "LD-PR-061",
    title: "Princess Cut 0.61 ct",
    brand: "Demo",
    category: "loose-diamonds",
    description:
      "Demo listing. Corners on a princess cut want protecting in the setting, which we work out at the bench. Figures are placeholders.",
    packSize: "1 stone",
    stockQty: 3,
    reorderPoint: 1,
    price: 1450,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "diamond-princess",
  },
  {
    sku: "LD-PE-085",
    title: "Pear Cut 0.85 ct — Champagne",
    brand: "Demo",
    category: "loose-diamonds",
    description:
      "Demo listing. A warm-bodied pear, the sort that suits a pendant. Colour description and weight are placeholders until a live stone is listed.",
    packSize: "1 stone",
    stockQty: 2,
    reorderPoint: 1,
    price: 1980,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "diamond-pear-champagne",
  },

  // --- Watch Parts ---------------------------------------------------------
  {
    sku: "WP-HANDS-01",
    title: "Watch Hands Set — Demo Assortment",
    brand: "Demo",
    category: "watch-parts",
    description: "Demo listing. Hour, minute and sweep hands sized to the calibre on the job.",
    packSize: "3 piece set",
    stockQty: 14,
    reorderPoint: 4,
    price: 22,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "watch-hands-set",
  },
  {
    sku: "WP-CROWN-24",
    title: "Crown Assortment — Stainless",
    brand: "Demo",
    category: "watch-parts",
    description: "Demo listing. Stainless crowns in the common tap sizes.",
    packSize: "24",
    stockQty: 7,
    reorderPoint: 2,
    price: 32,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "watch-crowns",
  },
  {
    sku: "WP-STEM-12",
    title: "Winding Stem Assortment",
    brand: "Demo",
    category: "watch-parts",
    description: "Demo listing. Stems for common calibres, cut to length at the bench.",
    packSize: "12",
    stockQty: 9,
    reorderPoint: 3,
    price: 18,
    currency: "CAD",
    visibility: "trade",
    demo: true,
    art: "watch-stems",
  },
  {
    sku: "WP-GASK-50",
    title: "Case Back Gaskets — Assorted",
    brand: "Demo",
    category: "watch-parts",
    description: "Demo listing. Assorted case back gaskets for a pressure test after service.",
    packSize: "50",
    stockQty: 18,
    reorderPoint: 5,
    price: 12.5,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "watch-gaskets",
  },

  // --- Watch Movements -----------------------------------------------------
  {
    sku: "MOV-AUTO",
    title: "Automatic Movement — Demo Calibre",
    brand: "Demo",
    category: "movements",
    description: "Demo listing. Placeholder automatic calibre for catalogue layout.",
    packSize: "1",
    stockQty: 6,
    reorderPoint: 2,
    price: 89,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "movement-automatic",
  },
  {
    sku: "MOV-QUARTZ",
    title: "Quartz Movement — Demo",
    brand: "Demo",
    category: "movements",
    description: "Demo listing. Placeholder quartz module with a standard stem height.",
    packSize: "1",
    stockQty: 20,
    reorderPoint: 5,
    price: 12.5,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "movement-quartz",
  },
  {
    sku: "MOV-HW",
    title: "Hand Wound Movement — Demo Calibre",
    brand: "Demo",
    category: "movements",
    description: "Demo listing. Placeholder hand wound calibre for catalogue layout.",
    packSize: "1",
    stockQty: 4,
    reorderPoint: 2,
    price: 76,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "movement-hand-wind",
  },

  // --- Watch Crystals ------------------------------------------------------
  {
    sku: "CRY-MIN-30",
    title: "Mineral Crystal 30.0 mm",
    brand: "Generic",
    category: "crystals",
    description: "Demo listing. Flat mineral crystal blank, measured across the seat.",
    packSize: "1",
    stockQty: 25,
    reorderPoint: 8,
    price: 4.5,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "crystal-mineral-flat",
  },
  {
    sku: "CRY-SAP-31",
    title: "Sapphire Crystal 31.0 mm",
    brand: "Generic",
    category: "crystals",
    description: "Demo listing. Lightly domed sapphire blank for a pressed case.",
    packSize: "1",
    stockQty: 8,
    reorderPoint: 2,
    price: 28,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "crystal-sapphire-domed",
  },
  {
    sku: "CRY-ACR-34",
    title: "Acrylic High Dome Crystal 34.0 mm",
    brand: "Generic",
    category: "crystals",
    description: "Demo listing. High dome acrylic for a vintage case, polishable on the wheel.",
    packSize: "1",
    stockQty: 16,
    reorderPoint: 5,
    price: 6.75,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "crystal-acrylic-high",
  },
  {
    sku: "CRY-MIN-38",
    title: "Mineral Crystal 38.0 mm",
    brand: "Generic",
    category: "crystals",
    description: "Demo listing. Large flat mineral blank for a diver or a chronograph case.",
    packSize: "1",
    stockQty: 11,
    reorderPoint: 4,
    price: 5.9,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "crystal-mineral-large",
  },

  // --- Batteries -----------------------------------------------------------
  {
    sku: "REN-377",
    title: "Watch Battery Renata 377",
    brand: "Renata",
    category: "batteries",
    description: "Swiss silver-oxide watch cell. Demo stock.",
    packSize: "1",
    stockQty: 120,
    reorderPoint: 24,
    price: 0.58,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "battery-cell-small",
  },
  {
    sku: "REN-364",
    title: "Watch Battery Renata 364",
    brand: "Renata",
    category: "batteries",
    description: "Swiss silver-oxide watch cell. Demo stock.",
    packSize: "1",
    stockQty: 80,
    reorderPoint: 20,
    price: 0.6,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "battery-cell-mid",
  },
  {
    sku: "REN-371",
    title: "Watch Battery Renata 371",
    brand: "Renata",
    category: "batteries",
    description: "Swiss silver-oxide watch cell. Demo stock.",
    packSize: "1",
    stockQty: 60,
    reorderPoint: 15,
    price: 0.98,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "battery-cell-wide",
  },
  {
    sku: "REN-395",
    title: "Watch Battery Renata 395",
    brand: "Renata",
    category: "batteries",
    description: "Swiss silver-oxide watch cell. Demo stock, off the shelf at the moment.",
    packSize: "1",
    stockQty: 0,
    reorderPoint: 12,
    price: 0.72,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "battery-cell-tall",
  },

  // --- Straps --------------------------------------------------------------
  {
    sku: "STR-102-BK",
    title: "Plain Grain Leather Strap — Black",
    brand: "Demo",
    category: "straps",
    description: "Demo listing. Grained calf strap; lug width chosen on the quote.",
    packSize: "1",
    stockQty: 40,
    reorderPoint: 10,
    price: 15,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "strap-black-grain",
  },
  {
    sku: "STR-102-BN",
    title: "Plain Grain Leather Strap — Brown",
    brand: "Demo",
    category: "straps",
    description: "Demo listing. Grained calf strap; lug width chosen on the quote.",
    packSize: "1",
    stockQty: 36,
    reorderPoint: 10,
    price: 15,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "strap-brown-grain",
  },
  {
    sku: "STR-109-BK",
    title: "Crocodile Grain Leather Strap — Black",
    brand: "Demo",
    category: "straps",
    description:
      "Demo listing. Crocodile-grain leather with a padded build; lug width chosen on the quote.",
    packSize: "1",
    stockQty: 14,
    reorderPoint: 4,
    price: 30,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "strap-croc-black",
  },
  {
    sku: "STR-114-TN",
    title: "Smooth Calf Leather Strap — Tan",
    brand: "Demo",
    category: "straps",
    description: "Demo listing. Smooth calf with a light edge finish; lug width chosen on the quote.",
    packSize: "1",
    stockQty: 22,
    reorderPoint: 6,
    price: 18.5,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "strap-tan-plain",
  },
  {
    sku: "STR-120-NV",
    title: "Ribbed Rubber Strap — Navy",
    brand: "Demo",
    category: "straps",
    description: "Demo listing. Ribbed rubber for a dive case; lug width chosen on the quote.",
    packSize: "1",
    stockQty: 30,
    reorderPoint: 8,
    price: 24,
    currency: "CAD",
    visibility: "public",
    demo: true,
    art: "strap-rubber-navy",
  },
];
