import type { Part } from "./types";

type Seed = Omit<Part, "id" | "createdAt" | "updatedAt">;

/** Demo catalogue inspired by a trade parts counter. Prices are placeholders. */
export const SEED_PARTS: Seed[] = [
  {
    sku: "REN-377",
    title: "Watch Battery Renata 377",
    brand: "Renata",
    category: "batteries",
    description: "Swiss silver-oxide watch cell. Demo stock.",
    packSize: "1",
    stockQty: 120,
    reorderPoint: 24,
    price: 0.58,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "REN-364",
    title: "Watch Battery Renata 364",
    brand: "Renata",
    category: "batteries",
    description: "Swiss silver-oxide watch cell. Demo stock.",
    packSize: "1",
    stockQty: 80,
    reorderPoint: 20,
    price: 0.6,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "REN-371",
    title: "Watch Battery Renata 371",
    brand: "Renata",
    category: "batteries",
    description: "Swiss silver-oxide watch cell. Demo stock.",
    packSize: "1",
    stockQty: 60,
    reorderPoint: 15,
    price: 0.98,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "BG-6767F",
    title: "Bergeon 6767-F Spring Bar Tool (Fine End)",
    brand: "Bergeon",
    category: "tools",
    description: "Fine-end spring bar tool. Demo listing.",
    packSize: "1",
    stockQty: 12,
    reorderPoint: 3,
    price: 25.07,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "BG-6767S",
    title: "Bergeon 6767-S Spring Bar Tool (Regular End)",
    brand: "Bergeon",
    category: "tools",
    description: "Regular-end spring bar tool. Demo listing.",
    packSize: "1",
    stockQty: 10,
    reorderPoint: 3,
    price: 25.07,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "BG-BLOWER",
    title: "Bergeon Rubber Dust Blower",
    brand: "Bergeon",
    category: "tools",
    description: "Bench dust blower. Demo listing.",
    packSize: "1",
    stockQty: 8,
    reorderPoint: 2,
    price: 23.0,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "BG-BBALL",
    title: "B-Ball for Screwdown Case Backs",
    brand: "Bergeon",
    category: "tools",
    description: "Case-back friction ball. Demo listing.",
    packSize: "1",
    stockQty: 15,
    reorderPoint: 4,
    price: 7.17,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "PERRIN-102-BK",
    title: "Plain Grain Genuine Leather Strap — Black",
    brand: "Demo",
    category: "straps",
    description: "Demo leather strap. Sizes selected on quote.",
    packSize: "1",
    stockQty: 40,
    reorderPoint: 10,
    price: 15.0,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "PERRIN-102-BN",
    title: "Plain Grain Genuine Leather Strap — Brown",
    brand: "Demo",
    category: "straps",
    description: "Demo leather strap. Sizes selected on quote.",
    packSize: "1",
    stockQty: 36,
    reorderPoint: 10,
    price: 15.0,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "PERRIN-109-BK",
    title: "Italian Crocodile Genuine Leather Strap — Black",
    brand: "Demo",
    category: "straps",
    description: "Demo premium strap. Sizes selected on quote.",
    packSize: "1",
    stockQty: 14,
    reorderPoint: 4,
    price: 30.01,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "CRY-MIN-30",
    title: "Mineral Crystal 30.0 mm",
    brand: "Generic",
    category: "crystals",
    description: "Demo mineral crystal blank.",
    packSize: "1",
    stockQty: 25,
    reorderPoint: 8,
    price: 4.5,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "CRY-SAP-31",
    title: "Sapphire Crystal 31.0 mm",
    brand: "Generic",
    category: "crystals",
    description: "Demo sapphire crystal blank.",
    packSize: "1",
    stockQty: 8,
    reorderPoint: 2,
    price: 28.0,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "MOV-NH35",
    title: "Automatic Movement — Demo Calibre",
    brand: "Demo",
    category: "movements",
    description: "Placeholder movement for catalogue layout.",
    packSize: "1",
    stockQty: 6,
    reorderPoint: 2,
    price: 89.0,
    currency: "CAD",
    visibility: "trade",
    demo: true,
  },
  {
    sku: "MOV-QUARTZ",
    title: "Quartz Movement — Demo",
    brand: "Demo",
    category: "movements",
    description: "Placeholder quartz movement.",
    packSize: "1",
    stockQty: 20,
    reorderPoint: 5,
    price: 12.5,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "CLK-QUARTZ",
    title: "Clock Quartz Movement",
    brand: "Demo",
    category: "clock-movements",
    description: "Demo clock movement with hands kit note.",
    packSize: "1",
    stockQty: 18,
    reorderPoint: 5,
    price: 9.75,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "WP-STEM",
    title: "Winding Stem Assortment",
    brand: "Demo",
    category: "watch-parts",
    description: "Demo stem assortment for common calibres.",
    packSize: "12",
    stockQty: 9,
    reorderPoint: 3,
    price: 18.0,
    currency: "CAD",
    visibility: "trade",
    demo: true,
  },
  {
    sku: "WP-CROWN",
    title: "Crown Assortment — Stainless",
    brand: "Demo",
    category: "watch-parts",
    description: "Demo stainless crowns.",
    packSize: "24",
    stockQty: 7,
    reorderPoint: 2,
    price: 32.0,
    currency: "CAD",
    visibility: "trade",
    demo: true,
  },
  {
    sku: "FIND-JUMP",
    title: "Jump Rings — Open, Assorted",
    brand: "Demo",
    category: "findings",
    description: "Demo jewellery findings pack.",
    packSize: "100",
    stockQty: 30,
    reorderPoint: 8,
    price: 6.5,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "FIND-CLASP",
    title: "Lobster Clasps — Gold Tone",
    brand: "Demo",
    category: "findings",
    description: "Demo clasps for repair and restringing.",
    packSize: "50",
    stockQty: 22,
    reorderPoint: 6,
    price: 11.0,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "PKG-TAG-S",
    title: "White String Tags — Small",
    brand: "Demo",
    category: "packaging",
    description: "Demo job tags.",
    packSize: "1000",
    stockQty: 5,
    reorderPoint: 2,
    price: 41.05,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "PKG-ZIP-35",
    title: "Mini-Grip Bags — 3 x 5",
    brand: "Demo",
    category: "packaging",
    description: "Demo ziplock bags.",
    packSize: "100",
    stockQty: 14,
    reorderPoint: 4,
    price: 2.08,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "CLN-OIL",
    title: "Watch Oil — Demo Grade",
    brand: "Demo",
    category: "cleaners",
    description: "Placeholder lubricant bottle.",
    packSize: "1",
    stockQty: 11,
    reorderPoint: 3,
    price: 14.5,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "CLN-CLEANER",
    title: "Ultrasonic Cleaner Concentrate",
    brand: "Demo",
    category: "cleaners",
    description: "Demo cleaner concentrate.",
    packSize: "1 L",
    stockQty: 6,
    reorderPoint: 2,
    price: 22.0,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
  {
    sku: "BG-SCREW",
    title: "Bergeon Ergonomic Screwdriver Set",
    brand: "Bergeon",
    category: "tools",
    description: "Demo screwdriver set listing.",
    packSize: "1",
    stockQty: 3,
    reorderPoint: 1,
    price: 214.85,
    currency: "CAD",
    visibility: "public",
    demo: true,
  },
];
